import ArticleSnippet from "./ArticleSnippet";

export default function ArticlesIntroduction() {
  return (
    <div className="md:pr-[90px]">

  {/* Author Card Mobile */}
       {/* Author Card */}
      <div className="rounded-[10px] bg-[#ffffff] p-4 text-[#1E3C8C] md:hidden flex items-center justify-between shadow-[0px_4px_3px_0px_#0000001A] mt-[-75px] mb-[35px] relative">
        <div className="flex items-start justify-between">
          <img
            src="/assets/articles/author.png"
            alt="Author"
            className="h-[67px] w-[67px] rounded-[10px] object-cover"
          />

    
        </div>
      <div className="autor-info">
        <h3 className="text-[14px] leading-[100%] italic font-bold">
          David James
        </h3>

        <p className="mt-[11px] text-[12px] leading-[110%] text-[#1E3C8C] font-[400]">
         CEO at Data Innovators 
        </p>
        </div>

              <a href="#">
                   <img src="assets/articles/in.png" className="w-[30px] h-[30px] object-contain"/>

          </a>
      </div>

      <h2 className="mb-1 text-[16px] md:text-[24px] font-bold italic text-[#1E3C8C] tracking-[1%]">
        Utilizing Renewable Energy for a Sustainable Tomorrow
      </h2>

      <div className="md:mt-5 md:space-y-8">
        <p className="text-[14px] md:text-[18px] leading-[150%] tracking-[-4%] text-[#1B1B1F]">
          Hi there! As a marketing manager in the renewable energy field, you may be looking for fresh ways to connect with your audience. Generative AI can be a fantastic asset for crafting engaging content. Let me share some insights.
        </p>

        <p className="text-[14px] md:text-[18px] leading-[150%] tracking-[-4%] text-[#1B1B1F]">
       Companies like Google emphasize the importance of high-quality content, whether it's written by humans or generated by AI like ChatGPT. The focus should be on creating original material that demonstrates expertise and builds trust, in line with Google’s E-E-A-T guidelines.
        </p>

        <p className="text-[14px] md:text-[18px] leading-[150%] tracking-[-4%] text-[#1B1B1F]">
        This means we should prioritize writing that centers on people, rather than just using AI to manipulate search rankings. Many experienced professionals want to share their knowledge but find writing challenging – that’s where Generative AI comes in.
        </p>

        <p className="text-[14px] md:text-[18px] leading-[150%] tracking-[-4%] text-[#1B1B1F]">
      Let’s discover how this technology can help us create valuable content that feels genuine and avoids the common traps of generic writing (spoiler alert: common pitfalls!). Get ready for an exciting learning journey!
        </p>


        <div className="featured-image mt-[30px]">
              {/* Hero */}
        <div className="overflow-hidden rounded-[6px] md:rounded-[20px] md:min-h-[450px]  md:max-h-[477px]">
          <img
            src="assets/articles/main.jpg"
            alt=""
            className="w-full rounded-[6px] md:rounded-[20px] object-cover"
          />
        </div>

        </div>
      </div>


{/* this will repeat */}


<ArticleSnippet
  images={[
    "assets/articles/image-1.jpg",
    "assets/articles/image-2.jpg",
  ]}
  title="Steering Clear of Common Mistakes in AI Writing for Renewable Energy"
  content={[
    "Jumping into AI tools like ChatGPT without a clear content strategy can lead to unsatisfactory results. A common error is focusing on quantity over quality – churning out numerous articles that lack personality and originality, blending into the vast sea of online content.",
    "Another challenge arises when we create duplicates instead of providing unique insights that genuinely benefit readers; this often occurs when AI is allowed to write without direction! Seasoned marketers and writers will tell you that infusing a human touch and adhering to clear guidelines are vital when using these technologies.",
    "Our aim should be to satisfy not just search engines but also the knowledge-hungry readers seeking trustworthy information. Keep your audience’s needs at the forefront while harnessing technology!",
  ]}
/>





<ArticleSnippet
  images={[
    "assets/articles/image-1.jpg",
    "assets/articles/image-2.jpg",
  ]}
  title="Steering Clear of Common Mistakes in AI Writing for Renewable Energy"
  content={[
    "Jumping into AI tools like ChatGPT without a clear content strategy can lead to unsatisfactory results. A common error is focusing on quantity over quality – churning out numerous articles that lack personality and originality, blending into the vast sea of online content.",
    "Another challenge arises when we create duplicates instead of providing unique insights that genuinely benefit readers; this often occurs when AI is allowed to write without direction! Seasoned marketers and writers will tell you that infusing a human touch and adhering to clear guidelines are vital when using these technologies.",
    "Our aim should be to satisfy not just search engines but also the knowledge-hungry readers seeking trustworthy information. Keep your audience’s needs at the forefront while harnessing technology!",
  ]}
/>
 <div className="mt-8 h-px bg-[#DDDDDD] md:hidden " />
    </div>
  );
}